# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [29]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [30]:
from sklearn.linear_model import Perceptron

In [31]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=1)

In [42]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [44]:
standardized_y_train = standardize.fit_transform(y_train.reshape(-1,1))


In [22]:
standardized_X_test[0:10,]

array([[-0.07829545,  1.70946556, -1.3642592 , -1.32113381],
       [-0.94366618, -1.53635513, -0.31929471, -0.0287203 ],
       [ 0.91069968, -0.4544149 ,  0.49345546,  0.4020842 ],
       [-0.57279301,  1.49307752, -1.30620562, -1.03393081],
       [ 2.51781676,  1.27668947,  1.65452712,  1.26369321],
       [ 0.53982651,  0.19474924,  0.6676162 ,  0.68928721],
       [ 1.28157285, -0.23802685,  0.89983054,  1.69449772],
       [-0.94366618,  1.27668947, -0.95788412, -1.03393081],
       [-1.43816375, -0.0216388 , -1.13204487, -1.32113381],
       [ 1.28157285, -0.0216388 ,  1.24815204,  1.69449772]])

In [ ]:
max_iter=50, eta0=0.15, tol=1e-3,

In [ ]:
from sklearn.linear_model import Perceptron

In [34]:
perceptron = Perceptron(random_state=1)
perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(random_state=1)

In [35]:
y_pred = perceptron.predict(standardized_X_test)

In [36]:
print(y_test)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2]


In [37]:
print(y_pred)

[0 1 1 0 2 2 2 0 0 2 1 0 2 2 2 0 1 2 0 0 1 2 2 0 2 1 0 0 1 2]


In [46]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.54      0.70        13
           2       0.50      1.00      0.67         6

    accuracy                           0.80        30
   macro avg       0.83      0.85      0.79        30
weighted avg       0.90      0.80      0.80        30



In [39]:
perceptron.score(standardized_X_test,y_test)

0.8